export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const PRODUCT_ACTIVE = 'ACTIVE_PRODUCT';
export const FLOVERS_PAGE = 'FLOVERS_PAGE';
export const INCREASE_COUNT_BOUQUET = 'INCREASE_COUNT_BOUQUET';
export const DECREASE_BOUQET_ACCOUNT = 'DECREASE_BOUQET_ACCOUNT';
export const SET_LANGUAGE = 'SET_LANGUAGE';
