export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const PRODUCT_ACTIVE = 'ACTIVE_PRODUCT';
export const FLOVERS_PAGE = 'FLOVERS_PAGE';
export const CHANGE_BOUQET_ACCOUNT = 'CHANGE_BOUQET_ACCOUNT';

//filter

export const CHANGE_FILTER = 'CHANGE_FILTER';
